config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  # get 'home/index'
  # root :to => "home#index"
  root :to => "courses#index"

  resources :courses do
    member do
      get :subscrible
    end
    resources :tasks, only: [:show]
  end
  get "/my_courses", to: "courses#my_courses"
  post "/payment_notification", to: "courses#payment_notification"
  # match '/payment_notification' => 'courses#payment_notification', :via => [:get, :post], :as => 'payment_notification'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_devise_message.erb
<%= devise_message_flash %>

app/views/shared/_footer.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Kampus RoR</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twiter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Instagram</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Goggle</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Kampus RoR
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_header.erb
<header>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Kampus Ku</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Courses", courses_path %></li>

          <% if !user_signed_in? %>
              <li><%= link_to "Sing Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
              <li>
                  <%= image_tag avatar_url(current_user), class: "circle responsive-img"  %>
              </li>
              <li>
                <a class="dropdown-button" href="#!" data-activates="dropdown1">
                  <%= current_user.name %>
                  <i class="material-icons right">arrow_drop_down</i></a>

              </li>
          <% end %>

          <ul id="dropdown1" class="dropdown-content">
            <li><%= link_to "My Profile", edit_user_registration_path %></li>
            <li><%= link_to "My Courses", my_courses_path %></li>
            <li><a href="#!">Setting</a></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>

          <ul id="dropdown2" class="dropdown-content">
            <li><%= link_to "My Profile", edit_user_registration_path %></li>
            <li><%= link_to "My Courses", my_courses_path %></li>

            <li><a href="#!">Setting</a></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </ul>

        <ul class="side-nav" id="mobile-demo">
          <li><%= link_to "Courses", courses_path %></li>
          <% if !user_signed_in? %>
              <li><%= link_to "Sing Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% else %>
              <li>
                <a class="dropdown-button" href="#!" data-activates="dropdown2">
                  <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>
                  <%= current_user.name %>
                  <i class="material-icons right">arrow_drop_down</i></a>
              </li>
          <% end %>
        </ul>

      </div>
    </div>

  </nav>
</header>

app/views/shared/_message.erb
<%= custom_bootstrap_flash %>